### ISSUE TITLE
Publish an update soon?

### ISSUE THREAD

**Issue by aw-was-here** [mojohaus/maven-native#13]
It's been several years since an update was published to the public (non-snapshot) maven repos.  Would there be a chance to get a new one relatively soon?  In particular, without extremely careful path management Apache Hadoop is suffering from the "command line too long" problem on Windows. That problem is supposed to be fixed by MOJO-2044, committed in 2014....

Thanks.

**Comment by aw-was-here** [comment]
ping @dantran , @gchauvet .

**Comment by hendriks73** [comment]
I would also appreciate a released update. Even if it's just the current state, simply because in the released 1.0-alpha-8 linking with *provided* dependencies seems to be broken (this seems fixed in 1.0-alpha-9-SNAPSHOT).

**Comment by hendriks73** [comment]
I'd like to add that I would love to release a project to maven central, but can't do that because I'm depending on the changes in alpha-9. :-/

**Comment by dantran** [comment]
sorry about the delay, will cut a new release as is soon

**Comment by dantran** [comment]
1.0-alpha-9 is is available at staging repo at https://oss.sonatype.org/content/groups/staging please test

**Comment by hendriks73** [comment]
I've tested yesterday with two projects. Thought I had posted this already, but apparently haven't.
Worked like charm for me.

**Comment by dantran** [comment]
released.
