### ISSUE TITLE
Plugin name does not adhere to Apache PMC guidelines

### ISSUE THREAD

**Issue by hendriks73** [mojohaus/maven-native#20]
Plugin names starting with *maven* aren't allowed anymore. See https://github.com/maven-nar/nar-maven-plugin/wiki/Frequently_Asked_Questions#q-why-was-the-plugin-renamed-to-nar-maven-plugin for details.

"maven-native" should probably be renamed to "native-maven-plugin", unless that's already taken.

**Comment by dantran** [comment]
as long as the plugin artifactId is not maven-xxxx-plugin we should be OK.

**Comment by hendriks73** [comment]
I didn't realize that's the exact pattern they don't like. Just wanted to make you aware of it (which apparently you are).

**Comment by ctubbsii** [comment]
The plugin name already follows the conventions. See https://github.com/mojohaus/maven-native/blob/master/native-maven-plugin/pom.xml#L10
This issue can be closed.
