### ISSUE TITLE
Execution of `/bin/sh -c` to execute javah results in error

### ISSUE THREAD

**Issue by ctubbsii** [mojohaus/maven-native#3]
When /bin/sh is symlink'd to bash (which it often is), the command results in the following error:

```
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
```

This is due to a missing semicolon in the command line. This is required by bash when executing a function as a one-liner. See http://tldp.org/LDP/abs/html/functions.html

This might be a bug in the upstream plexus Commandline or it might be a bug in how this plugin is using it. I can't tell with certainty. If it is a bug upstream. It might be fixed in a newer version of the plexus dependency.

**Comment by ctubbsii** [comment]
This bug is fixed in newer versions of plexus-utils. See my full analysis at codehaus-plexus/plexus-utils#14 . Updating to a newer version of plexus-utils and doing a new release to Maven Central will fix the issue. Thanks.

**Comment by ctubbsii** [comment]
If there's any way this could be patched to use the newer version of plexus-utils and released, I would greatly appreciate it. This bug is a big pain for me.

**Comment by ctubbsii** [comment]
This bug should be easily fixed by bumping to the newer version of plexus-utils and releasing... I'd be happy to help test, or do a PR... but so far, I haven't even seen a response from a maintainer, and I'm not sure how to proceed.

**Comment by hendriks73** [comment]
I'm not the maintainer, but posting a PR seems like the sensible way to go.
