### ISSUE TITLE
push 1.0-alpha-10 to central?

### ISSUE THREAD

**Issue by ekoepfle** [mojohaus/maven-native#31]
I came across a duplicate compiler outputs issue, and I noticed you clear the outputs in release alpha-10.  Would you mind pushing that up to maven central?  I don't see it here:

http://repo1.maven.org/maven2/org/codehaus/mojo/native-maven-plugin/

I came across the issue while working with JNI & scoverage.  Scoverage runs 2 compile->test phases.  One is the target build, and the other is their instrumentation run. I have tried all of my maven tricks to get these 2 plugins to play nicely, but in the end I keep getting 2 identical native-compiles passed to gcc.  At the root the List[File] of compiles in the PluginContext persists across multiple compile phases.  I was thinking of a PR as a Set, but I think that clear() might work too.

**Comment by dantran** [comment]
please test out https://oss.sonatype.org/content/repositories/orgcodehausmojo-1146  
or build from tag maven-native-1.0-alpha-11

**Comment by ekoepfle** [comment]
thanks, I will give these a try

**Comment by hendriks73** [comment]
In any case, pushing to central would be great... :-)

**Comment by ekoepfle** [comment]
the alpha-11 version does appear to fix the duplicate compiler output paths issue.  Agree with @hendriks73 , it would be nice to see it pop up in central so on-prem proxy repos pick it up.

**Comment by dantran** [comment]
pushed. Thanks for testing
