### ISSUE TITLE
Building multiple libraries

### ISSUE THREAD

**Issue by felixcrazzolara** [mojohaus/maven-native#66]
Is it possible to use maven-native to build multiple libraries? I tried to insert `<plugin>...native-maven-plugin...</plugin>` multiple times, but I found that a `pom.xml` only allows a single unique `groupId:artifactId` pair. I also looked at the documentation and searched the web, but wasn't able to find an example or an explanation how to do this.

**Comment by jbrentnell** [comment]
This is really a Maven issue.  Maven really encourages a 1-to-1 correspondence between pom files and artifacts like libraries.  You can attach other artifacts within the pom file like java-doc or source code.  But for libraries, you should think in terms of 1 pom file produces 1 library.  

I hope this helps,
